import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import PrelineScript from "./components/PrelineScript";
import Footer from "./components/Footer";
import SideMenu from "./components/SideMenu";
import { AuthProvider } from "@/app//lib/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-neutral-900`}
      >
        <AuthProvider>
          <div className="flex h-screen overflow-hidden">
            <SideMenu />
            <div className="flex flex-col flex-1 w-0 overflow-hidden">
              <Header />
              <main className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8">
                {children}
              </main>
              <Footer />
            </div>
          </div>
        </AuthProvider>
        <PrelineScript />
      </body>
    </html>
  );
}
